version: '2'
services:
  elixir:
    build: .
    volumes:
      - .:/home/docker/udemy_elixir
    command: bash -c "cd discuss && mix local.hex --force && mix phoenix.server"
    ports:
      - "4000:4000"
    depends_on:
      - postgres  
  postgres:
   image: postgres:9.6.1
   ports:
    - "5432:5432"
   environment:
     POSTGRES_USER: discuss
     POSTGRES_PASSWORD: discuss
     POSTGRES_DB: discuss_dev
   volumes:
     - ./dockerdata/postgresql:/var/lib/postgresql
